### ISSUE TITLE
docker的文件在服务器上运行mysql及elasticsearch报错

### ISSUE THREAD

**Issue by bluemarks** [wayn111/waynboot-mall#24]
当我使用代码自带的docker-compose-es7-rabbitmq-redis-mysql.yml配置文件以及附带的多个文件夹打包上传到我的虚拟机中并使用docker-compose up -d 命令运行，我删除了配置文件中的host映射，但是成功运行的只有redis和rabbitmq，mysql与elasticsearch并没有成功运行，docker的mysql日志爆出了一连串Read-only file system错误，elasticsearch报错
ElasticsearchException[failed to bind service]; nested: AccessDeniedException[/usr/share/elasticsearch/data/nodes];
Likely root cause: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes

**Comment by wayn111** [comment]
目录权限问题？建议设置chmod -R 777 试试

**Comment by bluemarks** [comment]
谢谢已经解决问题了，没有使用docker而是直接跑项目解决了

**Comment by shenghuang147** [comment]
> 目录权限问题？建议设置chmod -R 777 试试

对于这个问题请参考：https://github.com/docker-library/mysql/issues/920#issuecomment-1308843838 这个issues，我这边确认添加 `user: mysql` 可以解决这个问题

另外 `network_mode: "host"` 与 `ports` 貌似在新版本的docker-compose有冲突。
参考链接：https://forums.docker.com/t/docker-errors-invalidargument-host-network-mode-is-incompatible-with-port-bindings/103492/2
