### ISSUE TITLE
请问如何部署生产环境？

### ISSUE THREAD

**Issue by Angious** [wayn111/waynboot-mall#3]
我是这么做的：
1. 接口项目打包成jar到服务器，分别运行waynboot-admin-api-1.1.0.jar 、waynboot-message-consumer-1.1.0.jar、 waynboot-mobile-api-1.1.0.jar这三个jar包
2. h5项目和admin项目分别通过build命令打包好上传到nginx运行目录下两个子目录（h5和admin）
但是出现一个问题，访问ip/h5、ip/admin无法正常调用接口，请问正确步骤应该是什么？

**Comment by wayn111** [comment]
要修改前端项目vue.config.js里内容中publicPath路径为你的nginx配置路径
